# Generated by Django 5.2.10 on 2026-01-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_photo_alter_member_koalm_number_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
